spring:
  datasource:
    url: jdbc:postgresql://city-db:5432/city
#    url: jdbc:postgresql://localhost:5438/city
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml