version: '3.8'
services:
  city-db:
    container_name: postgres-city
    image: postgres:14.1
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: city

  city-service:
    container_name: city-service
    image: city-service:latest
    build: city-list/
    ports:
      - "8080:8080"
    depends_on:
      - city-db

  angular-service:
    container_name: city-list-angular
    build: frontend-city-list/
    ports:
      - "4200:4200"
    depends_on:
      - city-service